# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-04 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u6587\u7ae0\u6807\u9898')),
                ('content', models.TextField(verbose_name='\u6587\u7ae0\u5185\u5bb9')),
                ('author', models.CharField(max_length=20, verbose_name='\u4f5c\u8005')),
                ('date', models.CharField(max_length=20, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('type', models.CharField(max_length=20, verbose_name='\u6587\u7ae0\u7c7b\u578b')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='\u8bc4\u8bba\u5185\u5bb9')),
                ('date', models.CharField(max_length=20, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
            ],
        ),
    ]
